[env]
RUST_TEST_THREADS = "1"
#PKG_CONFIG_ALLOW_CROSS = "1"

#[build]
#rustflags = ["--cfg", "tokio_unstable"]
#
#[target.x86_64]
#linker = "clang"
#rustflags = ["-C", "link-arg=-fuse-ld=mold"]
#
#[target.x86_64-unknown-linux-gnu]
#linker = "clang"
#rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]
#
#[target.x86_64-unknown-linux-musl]
#linker = "clang"
#rustflags = [
#    "-C",
#    "link-arg=-fuse-ld=/usr/bin/mold",
#    "-C",
#    "target-feature=-crt-static",
#]
#
