[env]
RUST_TEST_THREADS = "1"
#TEST_REDIS_URL = "redis://127.0.0.1:6379"
#TEST_MYSQL_URL = "mysql://maria:maria@127.0.0.1:3306/test"
#PKG_CONFIG_ALLOW_CROSS = "1"

#[build]
#rustflags = ["--cfg", "tokio_unstable"]

# [target.x86_64]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=mold"]
 
# [target.x86_64-unknown-linux-gnu]
# linker = "clang"
# rustflags = ["-C", "link-arg=-fuse-ld=/usr/bin/mold"]

#[target.x86_64-unknown-linux-musl]
#linker = "clang"
#rustflags = [
#    "-C",
#    "link-arg=-fuse-ld=/usr/bin/mold",
#    "-C",
#    "target-feature=-crt-static",
#]
#
#

[term]
#quiet = false          # whether cargo output is quiet
#verbose = true         # whether cargo provides verbose output
color = 'auto'         # whether cargo colorizes output
hyperlinks = true      # whether cargo inserts links into output
unicode = true         # whether cargo can render output using non-ASCII unicode characters
progress.when = 'auto' # whether cargo shows progress bar
#progress.width = 80    # width of progress bar
